---
# file: roles/atomic_cli/tasks/main.yml
# main atomic cli role tasks
- name: set hostname
  hostname: name="atomiccli.example.com"
  with_indexed_items: "{{ groups['ATOMIC_CLI'] }}"
  when: "'ATOMIC_CLI' in groups"
  tags: atomic_cli
