# file: roles/rhua/tasks/extra_files.yml
# upload a zip file containing extra files that might be needed for some tests (e.g. entitlement certificate, RPMs for custom repos)

- name: upload the zip file containing an entitlement certificate and custom RPMs 
  copy: src="{{ extra_files }}" dest=/tmp/extra_files.zip
  register: extra_files_uploaded
  tags: rhua
  
- name: unzip the zip file 
  shell: "cd /tmp && unzip /tmp/extra_files.zip"
  when: extra_files_uploaded|success
  tags: rhua