---
# file: roles/rhua/tasks/main.yml
# tasks related to rhua setup
- name: set hostname
  hostname: name=rhua.example.com
  tags: rhua

- include: ssh.yml
- include: mongodb.yml

- name: install rhui-installer
  package: name=rhui-installer state=present
  register: install_rhui_installer
  tags: rhua

- name: call rhui installer if nfs
  command: rhui-installer --rhua-hostname=rhua.example.com --remote-fs-server=nfs.example.com:/export
  when: install_rhui_installer is changed and 'NFS' in groups and groups['NFS']|length > 0
  tags: rhua

- name: call rhui installer if gluster
  command: rhui-installer --rhua-hostname=rhua.example.com --remote-fs-server="{{ 'cds01.example.com:rhui_content_' + hostvars[groups['GLUSTER'][0]]['r'] }}" --remote-fs-type=glusterfs
  when: install_rhui_installer is success and 'GLUSTER' in groups and groups['GLUSTER']|length > 0
  tags: rhua

- name: get the initial rhui-manager password
  command: awk '/rhui_manager_password:/ { print $2 }' /etc/rhui-installer/answers.yaml
  register: password
  tags: rhua

- name: check if rhui-manager can run
  command: rhui-manager --username admin --password {{ password.stdout }} status
  register: rhuimanagercmd
  tags: rhua

- name: print the output from rhui-manager
  debug:
    var: rhuimanagercmd.stdout
