---
# file: roles/rhua/tasks/main.yml
# tasks related to rhua setup
- name: set hostname
  hostname: name=rhua.example.com
  tags: rhua

- include: ssh.yml

- name: install rhui-installer
  yum: name=rhui-installer state=present
  register: install_rhui_installer
  tags: rhua

- name: call rhui installer
  command: rhui-installer --remote-fs-server=nfs.example.com:/export
  when: "{{install_rhui_installer|changed and 'NFS' in groups and groups['NFS']|length > 0 }}"
  tags: rhua
