---
# file: roles/nfs/tasks/main.yml
# deploy & configure nfs server

- name: set hostname
  hostname: name="nfs.example.com"
  when: "'NFS' in groups"
  tags: nfs


- name: checking nfs-utils install
  package: name=nfs-utils state=present
  tags: nfs

- name: create storage volume directory
  file: path=/export state=directory
  tags: nfs

- name: format storage volume device
  filesystem:
    fstype: xfs
    dev: /dev/xvdb
  tags: nfs

- name: mount storage volume filesystem
  mount:
    path: /export
    src: /dev/xvdb
    fstype: xfs
    state: mounted
  tags: nfs

- name: start rpcbind service
  service: name=rpcbind state=started enabled=yes
  tags: nfs

- name: start nfs service if RHEL6
  service: name=nfs state=started enabled=yes
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6
  tags: nfs

- name: entry info in /etc/exports
  template: src=exports.j2 dest=/etc/exports
  notify: restart nfs
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6
  tags: nfs

- name: start nfs-server service if RHEL7
  service: name=nfs-server state=started enabled=yes
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7
  tags: nfs

- name: entry info in /etc/exports
  template: src=exports.j2 dest=/etc/exports
  notify: restart nfs-server
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7
  tags: nfs
