---
# file: roles/nfs/tasks/main.yml
# deploy & configure nfs server

- name: set hostname
  hostname: name="nfs.example.com"
  when: "'NFS' in groups"
  tags: nfs


- name: checking nfs-utils install
  package: name=nfs-utils state=present
  tags: nfs

- name: create storage volume directory
  file: path=/export state=directory
  tags: nfs

- name: format storage volume device
  filesystem:
    fstype: xfs
    dev: /dev/xvdb
  tags: nfs

- name: mount storage volume filesystem
  mount:
    path: /export
    src: /dev/xvdb
    fstype: xfs
    state: mounted
  tags: nfs

- name: start the rpcbind service
  service: name=rpcbind state=started enabled=yes
  tags: nfs

- name: start the nfs-server service
  service: name=nfs-server state=started enabled=yes
  tags: nfs

- name: set up the /etc/exports file
  template: src=exports.j2 dest=/etc/exports
  notify: restart nfs-server
  tags: nfs
