---
# file: roles/nfs/tasks/main.yml
# deploy & configure nfs server

- name: set hostname
  hostname: name="nfs.example.com"
  when: "'NFS' in groups"
  tags: nfs


- name: checking nfs-utils install
  package: name=nfs-utils state=present
  tags: nfs

- name: create volume
  file: path=/export state=directory
  tags: nfs

- name: start rpcbind service
  service: name=rpcbind state=started enabled=yes
  tags: nfs

- name: start nfs service if RHEL6
  service: name=nfs state=started enabled=yes
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6
  tags: nfs

- name: start nfs-server service if RHEL7
  systemd: name=nfs-server state=started enabled=yes
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7
  tags: nfs

- name: entry info in /etc/exports
  template: src=exports.j2 dest=/etc/exports
  notify: restart nfs
  tags: nfs
