---
# file: site.yml
# top-level deployment playbook
- hosts: all
  roles:
  - common

- include: dns.yml
- include: filesystem.yml
- include: gluster.yml
- include: rhua.yml
- include: haproxy.yml
- include: cds.yml
- include: cli.yml
- include: atomic_cli.yml
- include: tests.yml
