---
# file: site.yml
# top-level deployment playbook
- hosts: all
  roles:
    - common

- include: dns.yml
- include: master.yml
- include: nfs.yml
- include: haproxy.yml
- include: rhua.yml
- include: cds.yml
- include: cli.yml
