---
# file: site.yml
# top-level deployment playbook
- hosts: all
  roles:
  - common

- include: dns.yml
- include: master.yml
- include: filesystem.yml
- include: rhua.yml
- include: haproxy.yml
- include: cds.yml
- include: cli.yml
- include: gluster.yml
