# file: roles/common/upgrade_all_pkg.yml
# update all paclages prior to rhui installation

- name: upgrade all packages
  package: name=* state=latest update_cache=yes
  when:  upgrade_all_pkg is defined and upgrade_all_pkg | bool
  tags: upgrade_all_pkg
