# file: roles/common/upgrade.yml
# update packages prior to rhui installation: the RHEL-8 Beta client configuration and/or all

- name: upgrade rh-amazon-rhui-client-beta on RHEL 8
  dnf: name=rh-amazon-rhui-client-beta state=latest update_cache=yes update_only=yes
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 8
  tags: upgrade_beta_client_pkg

- name: upgrade all packages
  package: name=* state=latest update_cache=yes
  when:  upgrade_all_pkg is defined and upgrade_all_pkg | bool and not atomic | default(False)
  tags: upgrade_all_pkg
