---
# file: roles/common/tasks/vim.yml
# install vim, which may not be installed by default but is so much better than vi
# N/A to Atomic hosts as packages cannot be installed there

- name: install vim
  package:
    name: vim
    state: present
  when: not atomic | default(False)
  tags: vim
