---
# file: roles/cli/tasks/main.yml
# main cli role tasks
- name: set hostname
  hostname: name="cli0{{ item.0 + 1 }}.example.com"
  with_indexed_items: "{{ groups['CLI'] }}"
  when: "'CLI' in groups and item.1 == inventory_hostname"
  tags: cli

- name: install docker if RHEL7
  package: name=docker state=present enablerepo=*extras*
  with_indexed_items: "{{ groups['CLI'] }}"
  when: >
    "'CLI' in groups" and
    ansible_os_family == "RedHat" and
    ansible_distribution_major_version|int == 7
  tags: cli
  
- name: enable and run docker
  service: name=docker state=started enabled=yes
  with_indexed_items: "{{ groups['CLI'] }}"
  when: >
    "'CLI' in groups" and
    ansible_os_family == "RedHat" and
    ansible_distribution_major_version|int == 7
  tags: cli

- name: install podman-docker if RHEL8
  package: name=podman-docker state=present
  with_indexed_items: "{{ groups['CLI'] }}"
  when: >
    "'CLI' in groups" and
    ansible_os_family == "RedHat" and
    ansible_distribution_major_version|int == 8
  tags: cli

- name: install fontpackages-filesystem if RHEL8 ARM64
  package: name=fontpackages-filesystem state=present
  with_indexed_items: "{{ groups['CLI'] }}"
  when: >
    "'CLI' in groups" and
    ansible_os_family == "RedHat" and
    ansible_distribution_major_version|int == 8 and
    ansible_architecture == "aarch64"
  tags: cli

- name: import Red Hat Beta GPG keys if RHEL 8
  rpm_key: key=/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta state=present
  when: >
    "'CLI' in groups" and
    ansible_os_family == "RedHat" and
    ansible_distribution_major_version|int == 8
  tags: cli
