---
# file: roles/cli/tasks/main.yml
# main cli role tasks
- name: set hostname
  hostname: name="cli0{{ item.0 + 1 }}.example.com"
  with_indexed_items: "{{ groups['CLI'] }}"
  when: "'CLI' in groups and item.1 == inventory_hostname"
  tags: cli

- name: install the docker package if RHEL7
  package: name=docker state=present enablerepo=*extras*
  with_indexed_items: "{{ groups['CLI'] }}"
  when: >
    "'CLI' in groups" and
    ansible_os_family == "RedHat" and
    ansible_distribution_major_version|int == 7
  tags: cli
  
- name: enable and run the docker service
  service: name=docker state=started enabled=yes
  with_indexed_items: "{{ groups['CLI'] }}"
  when: >
    "'CLI' in groups" and
    ansible_os_family == "RedHat" and
    ansible_distribution_major_version|int == 7
  tags: cli

- name: install the podman-docker package if RHEL8
  package: name=podman-docker state=present
  with_indexed_items: "{{ groups['CLI'] }}"
  when: >
    "'CLI' in groups" and
    ansible_os_family == "RedHat" and
    ansible_distribution_major_version|int == 8
  tags: cli

- name: create the platform-python symlink if RHEL6
  file:
    src: /usr/bin/python
    dest: /usr/libexec/platform-python
    state: link
  when: >
    "'CLI' in groups" and
    ansible_os_family == "RedHat" and
    ansible_distribution_major_version|int == 6
  tags: cli
