---
# file: roles/haproxy/tasks/main.yml
# deploy & configure named on a host

- name: set hostname
  hostname: name="hap0{{ item.0 + 1 }}.example.com"
  with_indexed_items: "{{ groups['HAPROXY'] }}"
  when: "'HAPROXY' in groups and item.1 == inventory_hostname"
  tags: haproxy

- name: copy remote haproxy rpm
  copy: src={{haproxy_rpm}} dest=/tmp
  when: >
    ansible_os_family == "RedHat" and
    ansible_distribution_major_version|int == 6 and
    haproxy_rpm is defined
  register: copy_haproxy_rpm_result
  tags: haproxy

- name: install haproxy rpm
  package: name='/tmp/{{haproxy_rpm|basename}}' state=present
  when: >
    ansible_os_family == "RedHat" and
    ansible_distribution_major_version|int == 6 and
    haproxy_rpm is defined and
    copy_haproxy_rpm_result|success
  tags: haproxy
