---
# file: roles/haproxy/tasks/main.yml
# deploy & configure named on a host

- name: set hostname
  hostname: name="hap0{{ item.0 + 1 }}.example.com"
  with_indexed_items: groups['HAPROXY']
  when: "'HAPROXY' in groups and item.1 == inventory_hostname"
  tags: haproxy

