#!/usr/bin/python
'''Unregister RHUI nodes from RHSM.'''

from __future__ import print_function

import stitches
from stitches.expect import ExpectFailed

from rhui3_tests_lib.helpers import Helpers
from rhui3_tests_lib.subscription import RHSMRHUI
from rhui3_tests_lib.util import Util

RHUA_HOSTNAME = "rhua.example.com"
CDS_HOSTNAMES = Util.get_cds_hostnames()
HA_HOSTNAME = "hap01.example.com"

print("Unregistering the nodes.")
for hostname in [RHUA_HOSTNAME] + CDS_HOSTNAMES + [HA_HOSTNAME]:
    CONNECTION = stitches.Connection(hostname, "root", "/root/.ssh/id_rsa_test")
    if not Helpers.is_registered(CONNECTION):
        print("%s is not registered, skipping." % hostname)
        continue
    try:
        RHSMRHUI.unregister_system(CONNECTION)
        print("Unregistered %s." % hostname)
    except ExpectFailed as err:
        print("An error occurred while unregistering %s:" % hostname)
        print(err)
