#!/usr/bin/python
'''Log in to RHUI, upload a certificate, and add a CDS and a HAProxy node. '''

from __future__ import print_function

from rhui3_tests_lib.conmgr import ConMgr
from rhui3_tests_lib.rhuimanager import RHUIManager
from rhui3_tests_lib.rhuimanager_entitlement import RHUIManagerEntitlements
from rhui3_tests_lib.rhuimanager_instance import RHUIManagerInstance, InstanceAlreadyExistsError

RHUA = ConMgr.connect()
CDS_HOSTNAME = ConMgr.get_cds_hostnames()[0]
HA_HOSTNAME = ConMgr.get_haproxy_hostnames()[0]

print("Logging in to RHUI.")
RHUIManager.initial_run(RHUA)

print("Uploading an entitlement certificate.")
RHUIManagerEntitlements.upload_rh_certificate(RHUA)

print("Adding a CDS (%s)." % CDS_HOSTNAME)
try:
    RHUIManagerInstance.add_instance(RHUA, "cds")
except InstanceAlreadyExistsError:
    print("Already added, never mind.")

print("Adding an HAProxy load balancer (%s)." % HA_HOSTNAME)
try:
    RHUIManagerInstance.add_instance(RHUA, "loadbalancers")
except InstanceAlreadyExistsError:
    print("Already added, never mind.")

print("To make client tests skip these steps, run: export RHUISKIPSETUP=1")
