#!/usr/bin/python
'''Unregister RHUI nodes from RHSM.'''

from __future__ import print_function

from stitches.expect import ExpectFailed

from rhui3_tests_lib.conmgr import ConMgr
from rhui3_tests_lib.helpers import Helpers
from rhui3_tests_lib.subscription import RHSMRHUI

RHUA_HOSTNAME = ConMgr.get_rhua_hostname()
CDS_HOSTNAMES = ConMgr.get_cds_hostnames()
HA_HOSTNAMES = ConMgr.get_haproxy_hostnames()

print("Unregistering the nodes.")
for hostname in [RHUA_HOSTNAME] + CDS_HOSTNAMES + HA_HOSTNAMES:
    CONNECTION = ConMgr.connect(hostname)
    if not Helpers.is_registered(CONNECTION):
        print("%s is not registered, skipping." % hostname)
        continue
    try:
        RHSMRHUI.unregister_system(CONNECTION)
        print("Unregistered %s." % hostname)
    except ExpectFailed as err:
        print("An error occurred while unregistering %s:" % hostname)
        print(err)
