#!/usr/bin/python
'''Remove certificates and unregister CDS and HAProxy nodes. '''

from __future__ import print_function

import stitches

from rhui3_tests_lib.rhuimanager import RHUIManager
from rhui3_tests_lib.rhuimanager_instance import RHUIManagerInstance, NoSuchInstance
from rhui3_tests_lib.rhuimanager_repo import RHUIManagerRepo

CONNECTION = stitches.Connection("rhua.example.com", "root", "/root/.ssh/id_rsa_test")
CDS = "cds01.example.com"
HA = "hap01.example.com"

print("Removing entitlement certificates.")
RHUIManager.remove_rh_certs(CONNECTION)

print("Unregistering the CDS.")
try:
    RHUIManagerInstance.delete(CONNECTION, "cds", [CDS])
except NoSuchInstance:
    print("Not registered, never mind.")

print("Unregistering the HAProxy load balancer.")
try:
    RHUIManagerInstance.delete(CONNECTION, "loadbalancers", [HA])
except NoSuchInstance:
    print("Not registered, never mind.")

print("Deleting leftover repositories (if there are any).")
if RHUIManagerRepo.list(CONNECTION):
    RHUIManagerRepo.delete_all_repos(CONNECTION)
else:
    print("There are none, never mind.")
